export const certifications = [
    "Instalador Eléctrico SEC Clase A",
    "Instalador Eléctrico SEC Clase B",
    "Instalador Eléctrico SEC Clase C",
    "Instalador Eléctrico SEC Clase D",
    "Instalador de Gas SEC Clase 1",
    "Instalador de Gas SEC Clase 2",
    "Instalador de Gas SEC Clase 3",
    "Operador de Grúa Horquilla",
    "Operador de Grúa Torre",
    "Operador de Maquinaria Pesada",
    "Rigger Alta Tonelaje",
    "Rigger Baja Tonelaje",
    "Trabajo en Altura",
    "Espacios Confinados",
    "Soldador Calificado 3G",
    "Soldador Calificado 4G",
    "Soldador Calificado 6G",
    "Prevención de Riesgos - Experto",
    "Prevención de Riesgos - Técnico",
    "Manipulación de Alimentos",
    "Manejo de Sustancias Peligrosas",
    "Primeros Auxilios",
    "Uso y Manejo de Extintores",
    "Andamiero Calificado",
    "Operador de Calderas"
];
