export const projectTypes = [
    "Edificación en altura",
    "Edificación baja",
    "Obras Viales",
    "Obras Hidráulicas",
    "Obras Portuarias",
    "Minería",
    "Energía",
    "Industrial",
    "Montaje Industrial",
    "Movimiento de Tierras",
    "Túneles",
    "Puentes",
    "Saneamiento",
    "Urbanización",
    "Restauración Patrimonial",
    "Casa",
    "Cabaña",
    "Remodelación",
    "Ampliación",
    "Quincho",
    "Piscina",
    "Cobertizo",
    "Reja/Cierre Perimetral"
];
