export const specialties = [
    "Albañil",
    "Carpintero",
    "Electricista",
    "Gasfíter",
    "Enfierrador",
    "Pintor",
    "Soldador",
    "Yesero",
    "Ceramista",
    "Techador",
    "Maestro Mayor",
    "Ayudante",
    "Jornal",
    "Capataz",
    "Topógrafo",
    "Operador de Maquinaria",
    "Rigger",
    "Prevencionista de Riesgos",
    "Trazador",
    "Instalador de Pisos",
    "Vidriero",
    "Mueblista",
    "Tabiquero",
    "Concretero",
    "Excavador"
];
