export const albures = [
    "Elver Galarga",
    "Rosa Melton",
    "Alma Madero",
    "Debora Melo",
    "Aquiles Brinco",
    "Elsa Pato",
    "Benito Camelo",
    "Susana Horia",
    "Larry Capija",
    "Monica Galindo",
    "Elvis Tek",
    "Paco Gerte",
    "Jorge Nitales",
    "Alan Brito",
    "Elsa Polindo",
    "Aitor Tilla",
    "Zoila Vaca",
    "Micho Tito",
    "Debora Cabezas",
    "Lucho Portuano",
    "Rosamel Ano",
    "Rosamel Fierro"
];
